version: '2.1'

services:
    db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./volumes/db_data:/var/lib/mysql
            - ./volumes/mysql_log:/var/log/mysql

    askhy:
        build:
            context: .
            dockerfile: compose/askhy/Dockerfile
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            DATABASE_HOST: db
            DATABASE_USER: root
            DATABASE_PASS: root
            DATABASE_NAME: test
            DATABASE_PORT: 3306
            APP_PORT: 80
        links:
            - db
        restart: always